<?php

namespace App\DataTransfer\Definitions;

use App\Models\Notification;
use App\Models\User;
use App\Support\DataTransfer\AbstractResourceDefinition;
use App\Support\DataTransfer\Column;

/**
 * Export only.
 *
 * Notifications are generated by the system as a record of things that
 * happened. Importing them would let a spreadsheet manufacture events that
 * never occurred, which is why this module answers false to supportsImport()
 * and offers no template.
 */
class NotificationDefinition extends AbstractResourceDefinition
{
    public function key(): string
    {
        return 'notifications';
    }

    public function modelClass(): string
    {
        return Notification::class;
    }

    public function label(): string
    {
        return __('notifications.notifications');
    }

    public function singularLabel(): string
    {
        return __('notifications.notifications');
    }

    public function icon(): string
    {
        return 'bi-bell';
    }

    public function indexRoute(): string
    {
        return 'notifications.index';
    }

    public function supportsImport(): bool
    {
        return false;
    }

    /** @return array<string, string> */
    public function permissions(): array
    {
        return [
            'view' => 'notification.view',
            'export' => 'notification.export',
        ];
    }

    /** @return array<int, Column> */
    protected function defineColumns(): array
    {
        return [
            Column::string('title')
                ->label(__('notifications.title'))
                ->width(28),

            Column::text('message')
                ->label(__('notifications.message'))
                ->width(40),

            Column::string('type')
                ->label(__('notifications.type'))
                ->width(16),

            Column::string('priority')
                ->label(__('notifications.priority'))
                ->width(14),

            Column::lookup('user_id', User::class, 'name')
                ->label(__('notifications.recipient'))
                ->width(20),

            Column::datetime('read_at')
                ->label(__('notifications.read_at'))
                ->width(18),

            Column::datetime('created_at')
                ->label(__('notifications.received_at'))
                ->exportOnly()
                ->width(18),
        ];
    }

    /** @return array<int, string> */
    protected function searchColumns(): array
    {
        return ['title', 'message'];
    }

    /** @return array<string, string> */
    protected function filters(): array
    {
        return [
            'type' => 'type',
            'priority' => 'priority',
        ];
    }

    /** @return array<string, string> */
    protected function defaultSort(): array
    {
        return ['created_at' => 'desc'];
    }

    /**
     * Notifications are system-generated events, cleared individually from the notification screen.
     */
    public function supportsBulkActions(): bool
    {
        return false;
    }
}
